[build]
  command = "npm run build"  # This tells Netlify to run npm run build during deployment
  publish = "dist"           # This is the directory Netlify will serve after the build

[build.environment]
  NODE_ENV = "production"    # Optional: Set environment variable if needed

[[redirects]]
  from = "/api/*"
  to = "https://api.netlify.com/api/v1/badges/d0587505-2462-4d10-bc8a-b1be4a04b7ba/deploy-status)](https://app.netlify.com/projects/splendid-travesseiro-6824b5/deploys)

"
  status = 200
  force = true
